---
layout: cv
title: Resume Drevin Rigby
---

Bachelor of Science in Accounting Brigham Young University - Idaho
•	GPA 3.96 
•	Data Science Certificate
•	Treasurer - Student Accounting Society


## Currently

Rudd and Company	Idaho Falls, Idaho
•	Prepared 1040, 1065, and 1120-S tax returns for individuals, partnerships, and s-corporations, ensuring accuracy and compliance with federal and state tax laws.
•	Analyzed financial statements, performed reconciliations, and recorded journal entries to identify discrepancies, improve financial accuracy, and support tax return preparation.
•	Assisted senior tax professionals in developing customized tax strategies to optimize after-tax income.


### Specialized and Experienced in

•	Tax software, data analytics, and automation, with proficiency in Excel, Excel VBA, SQL, Lacerte, Tax Caddy, XCM/CCH Axcess Workflow, SurePrep, IDEA, Python, VS Code, and Power BI.
•	Certifications: Microsoft Excel Educator Certificate, Bloomberg Market Concepts Certificate
•	Languages: Fluent in speaking, reading, and writing in Spanish.



### Research interests

Accounting Theory


## Education

Bachelor of Science in Accounting Brigham Young University - Idaho


## Leadership

Treasurer
Student Accounting Society - BYU-Idaho	                                        April – August 2025
Rexburg, Idaho
•	Designed and launched a strategic recruiting initiative that more than doubled semester membership revenue—from $850 to nearly $1,750.
•	Led advertising efforts that boosted weekly meeting attendance by 37%, significantly enhancing member engagement and program visibility.

Full-Time Volunteer	August 2020 - August 2022
	
The Church of Jesus Christ of Latter-day Saints	Quetzaltenango, Guatemala
•	Directed 50+ young adults, conducted in-depth team training, planned activities, and followed up weekly and monthly on work as a pod leader for seven months.
•	Led training with a goal of improving teaching techniques, interpersonal skills, overall effectiveness as well as encouraged strong morale and optimism. On average 4-5 mock scenarios were executed weekly to hone and improve interpersonal skills and teaching effectiveness.


<!-- ### Footer

Last updated: May 2013 -->